/*
 * This file is generated by jOOQ.
 */
package vn.thanhlong.db;


import vn.thanhlong.db.tables.Catalog;
import vn.thanhlong.db.tables.Customer;
import vn.thanhlong.db.tables.Invoice;
import vn.thanhlong.db.tables.InvoiceDetail;
import vn.thanhlong.db.tables.LoginHistory;
import vn.thanhlong.db.tables.Product;
import vn.thanhlong.db.tables.User;


/**
 * Convenience access to all tables in onlineshopmall
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>onlineshopmall.catalog</code>.
     */
    public static final Catalog CATALOG = Catalog.CATALOG;

    /**
     * The table <code>onlineshopmall.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>onlineshopmall.invoice</code>.
     */
    public static final Invoice INVOICE = Invoice.INVOICE;

    /**
     * The table <code>onlineshopmall.invoice_detail</code>.
     */
    public static final InvoiceDetail INVOICE_DETAIL = InvoiceDetail.INVOICE_DETAIL;

    /**
     * The table <code>onlineshopmall.login_history</code>.
     */
    public static final LoginHistory LOGIN_HISTORY = LoginHistory.LOGIN_HISTORY;

    /**
     * The table <code>onlineshopmall.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>onlineshopmall.user</code>.
     */
    public static final User USER = User.USER;
}
