/*
 * This file is generated by jOOQ.
 */
package vn.thanhlong.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import vn.thanhlong.db.tables.Catalog;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogRecord extends UpdatableRecordImpl<CatalogRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1960234487;

    /**
     * Setter for <code>onlineshopmall.catalog.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>onlineshopmall.catalog.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>onlineshopmall.catalog.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>onlineshopmall.catalog.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>onlineshopmall.catalog.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>onlineshopmall.catalog.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Catalog.CATALOG.ID;
    }

    @Override
    public Field<String> field2() {
        return Catalog.CATALOG.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Catalog.CATALOG.PARENT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getParentId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getParentId();
    }

    @Override
    public CatalogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CatalogRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CatalogRecord value3(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public CatalogRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CatalogRecord
     */
    public CatalogRecord() {
        super(Catalog.CATALOG);
    }

    /**
     * Create a detached, initialised CatalogRecord
     */
    public CatalogRecord(Integer id, String name, Integer parentId) {
        super(Catalog.CATALOG);

        set(0, id);
        set(1, name);
        set(2, parentId);
    }
}
