/*
 * This file is generated by jOOQ.
 */
package vn.thanhlong.db.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import vn.thanhlong.db.tables.InvoiceDetail;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceDetailRecord extends UpdatableRecordImpl<InvoiceDetailRecord> implements Record4<Integer, Integer, BigDecimal, Integer> {

    private static final long serialVersionUID = 1452779626;

    /**
     * Setter for <code>onlineshopmall.invoice_detail.invoice_id</code>.
     */
    public void setInvoiceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice_detail.invoice_id</code>.
     */
    public Integer getInvoiceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>onlineshopmall.invoice_detail.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice_detail.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>onlineshopmall.invoice_detail.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice_detail.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>onlineshopmall.invoice_detail.quanty</code>.
     */
    public void setQuanty(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice_detail.quanty</code>.
     */
    public Integer getQuanty() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, BigDecimal, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, BigDecimal, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return InvoiceDetail.INVOICE_DETAIL.INVOICE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return InvoiceDetail.INVOICE_DETAIL.PRODUCT_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return InvoiceDetail.INVOICE_DETAIL.PRICE;
    }

    @Override
    public Field<Integer> field4() {
        return InvoiceDetail.INVOICE_DETAIL.QUANTY;
    }

    @Override
    public Integer component1() {
        return getInvoiceId();
    }

    @Override
    public Integer component2() {
        return getProductId();
    }

    @Override
    public BigDecimal component3() {
        return getPrice();
    }

    @Override
    public Integer component4() {
        return getQuanty();
    }

    @Override
    public Integer value1() {
        return getInvoiceId();
    }

    @Override
    public Integer value2() {
        return getProductId();
    }

    @Override
    public BigDecimal value3() {
        return getPrice();
    }

    @Override
    public Integer value4() {
        return getQuanty();
    }

    @Override
    public InvoiceDetailRecord value1(Integer value) {
        setInvoiceId(value);
        return this;
    }

    @Override
    public InvoiceDetailRecord value2(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public InvoiceDetailRecord value3(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public InvoiceDetailRecord value4(Integer value) {
        setQuanty(value);
        return this;
    }

    @Override
    public InvoiceDetailRecord values(Integer value1, Integer value2, BigDecimal value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceDetailRecord
     */
    public InvoiceDetailRecord() {
        super(InvoiceDetail.INVOICE_DETAIL);
    }

    /**
     * Create a detached, initialised InvoiceDetailRecord
     */
    public InvoiceDetailRecord(Integer invoiceId, Integer productId, BigDecimal price, Integer quanty) {
        super(InvoiceDetail.INVOICE_DETAIL);

        set(0, invoiceId);
        set(1, productId);
        set(2, price);
        set(3, quanty);
    }
}
