/*
 * This file is generated by jOOQ.
 */
package vn.thanhlong.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import vn.thanhlong.db.tables.Invoice;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceRecord extends UpdatableRecordImpl<InvoiceRecord> implements Record6<Integer, Long, Integer, String, Boolean, String> {

    private static final long serialVersionUID = 1469089257;

    /**
     * Setter for <code>onlineshopmall.invoice.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>onlineshopmall.invoice.date_create</code>.
     */
    public void setDateCreate(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice.date_create</code>.
     */
    public Long getDateCreate() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>onlineshopmall.invoice.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>onlineshopmall.invoice.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>onlineshopmall.invoice.status</code>.
     */
    public void setStatus(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>onlineshopmall.invoice.message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>onlineshopmall.invoice.message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, Integer, String, Boolean, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Long, Integer, String, Boolean, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Invoice.INVOICE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Invoice.INVOICE.DATE_CREATE;
    }

    @Override
    public Field<Integer> field3() {
        return Invoice.INVOICE.CUSTOMER_ID;
    }

    @Override
    public Field<String> field4() {
        return Invoice.INVOICE.USER_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return Invoice.INVOICE.STATUS;
    }

    @Override
    public Field<String> field6() {
        return Invoice.INVOICE.MESSAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDateCreate();
    }

    @Override
    public Integer component3() {
        return getCustomerId();
    }

    @Override
    public String component4() {
        return getUserId();
    }

    @Override
    public Boolean component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getMessage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDateCreate();
    }

    @Override
    public Integer value3() {
        return getCustomerId();
    }

    @Override
    public String value4() {
        return getUserId();
    }

    @Override
    public Boolean value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getMessage();
    }

    @Override
    public InvoiceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public InvoiceRecord value2(Long value) {
        setDateCreate(value);
        return this;
    }

    @Override
    public InvoiceRecord value3(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public InvoiceRecord value4(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public InvoiceRecord value5(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public InvoiceRecord value6(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public InvoiceRecord values(Integer value1, Long value2, Integer value3, String value4, Boolean value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceRecord
     */
    public InvoiceRecord() {
        super(Invoice.INVOICE);
    }

    /**
     * Create a detached, initialised InvoiceRecord
     */
    public InvoiceRecord(Integer id, Long dateCreate, Integer customerId, String userId, Boolean status, String message) {
        super(Invoice.INVOICE);

        set(0, id);
        set(1, dateCreate);
        set(2, customerId);
        set(3, userId);
        set(4, status);
        set(5, message);
    }
}
