/*
 * This file is generated by jOOQ.
 */
package vn.thanhlong.db.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import vn.thanhlong.db.tables.Product;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record8<Integer, String, String, BigDecimal, Integer, String, Long, Integer> {

    private static final long serialVersionUID = -1483600250;

    /**
     * Setter for <code>onlineshopmall.product.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>onlineshopmall.product.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>onlineshopmall.product.decription</code>.
     */
    public void setDecription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.decription</code>.
     */
    public String getDecription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>onlineshopmall.product.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>onlineshopmall.product.discount</code>.
     */
    public void setDiscount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.discount</code>.
     */
    public Integer getDiscount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>onlineshopmall.product.image_link</code>.
     */
    public void setImageLink(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.image_link</code>.
     */
    public String getImageLink() {
        return (String) get(5);
    }

    /**
     * Setter for <code>onlineshopmall.product.date_create</code>.
     */
    public void setDateCreate(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.date_create</code>.
     */
    public Long getDateCreate() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>onlineshopmall.product.catalog_id</code>.
     */
    public void setCatalogId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>onlineshopmall.product.catalog_id</code>.
     */
    public Integer getCatalogId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, BigDecimal, Integer, String, Long, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, BigDecimal, Integer, String, Long, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.ID;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Product.PRODUCT.DECRIPTION;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Product.PRODUCT.PRICE;
    }

    @Override
    public Field<Integer> field5() {
        return Product.PRODUCT.DISCOUNT;
    }

    @Override
    public Field<String> field6() {
        return Product.PRODUCT.IMAGE_LINK;
    }

    @Override
    public Field<Long> field7() {
        return Product.PRODUCT.DATE_CREATE;
    }

    @Override
    public Field<Integer> field8() {
        return Product.PRODUCT.CATALOG_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDecription();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public Integer component5() {
        return getDiscount();
    }

    @Override
    public String component6() {
        return getImageLink();
    }

    @Override
    public Long component7() {
        return getDateCreate();
    }

    @Override
    public Integer component8() {
        return getCatalogId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDecription();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public Integer value5() {
        return getDiscount();
    }

    @Override
    public String value6() {
        return getImageLink();
    }

    @Override
    public Long value7() {
        return getDateCreate();
    }

    @Override
    public Integer value8() {
        return getCatalogId();
    }

    @Override
    public ProductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductRecord value3(String value) {
        setDecription(value);
        return this;
    }

    @Override
    public ProductRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public ProductRecord value5(Integer value) {
        setDiscount(value);
        return this;
    }

    @Override
    public ProductRecord value6(String value) {
        setImageLink(value);
        return this;
    }

    @Override
    public ProductRecord value7(Long value) {
        setDateCreate(value);
        return this;
    }

    @Override
    public ProductRecord value8(Integer value) {
        setCatalogId(value);
        return this;
    }

    @Override
    public ProductRecord values(Integer value1, String value2, String value3, BigDecimal value4, Integer value5, String value6, Long value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, String name, String decription, BigDecimal price, Integer discount, String imageLink, Long dateCreate, Integer catalogId) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, name);
        set(2, decription);
        set(3, price);
        set(4, discount);
        set(5, imageLink);
        set(6, dateCreate);
        set(7, catalogId);
    }
}
