/*
 * This file is generated by jOOQ.
 */
package vn.thanhlong.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import vn.thanhlong.db.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<String, String, String, String, Boolean, String, String, Long, String, String> {

    private static final long serialVersionUID = 1324131591;

    /**
     * Setter for <code>onlineshopmall.user.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>onlineshopmall.user.hash_value</code>.
     */
    public void setHashValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.hash_value</code>.
     */
    public String getHashValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>onlineshopmall.user.salt</code>.
     */
    public void setSalt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.salt</code>.
     */
    public String getSalt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>onlineshopmall.user.full_name</code>.
     */
    public void setFullName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.full_name</code>.
     */
    public String getFullName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>onlineshopmall.user.gender</code>.
     */
    public void setGender(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.gender</code>.
     */
    public Boolean getGender() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>onlineshopmall.user.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>onlineshopmall.user.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>onlineshopmall.user.date_create</code>.
     */
    public void setDateCreate(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.date_create</code>.
     */
    public Long getDateCreate() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>onlineshopmall.user.forget_password</code>.
     */
    public void setForgetPassword(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.forget_password</code>.
     */
    public String getForgetPassword() {
        return (String) get(8);
    }

    /**
     * Setter for <code>onlineshopmall.user.active_mail</code>.
     */
    public void setActiveMail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>onlineshopmall.user.active_mail</code>.
     */
    public String getActiveMail() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, String, String, Boolean, String, String, Long, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, String, String, Boolean, String, String, Long, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return User.USER.HASH_VALUE;
    }

    @Override
    public Field<String> field3() {
        return User.USER.SALT;
    }

    @Override
    public Field<String> field4() {
        return User.USER.FULL_NAME;
    }

    @Override
    public Field<Boolean> field5() {
        return User.USER.GENDER;
    }

    @Override
    public Field<String> field6() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return User.USER.PHONE;
    }

    @Override
    public Field<Long> field8() {
        return User.USER.DATE_CREATE;
    }

    @Override
    public Field<String> field9() {
        return User.USER.FORGET_PASSWORD;
    }

    @Override
    public Field<String> field10() {
        return User.USER.ACTIVE_MAIL;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getHashValue();
    }

    @Override
    public String component3() {
        return getSalt();
    }

    @Override
    public String component4() {
        return getFullName();
    }

    @Override
    public Boolean component5() {
        return getGender();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getPhone();
    }

    @Override
    public Long component8() {
        return getDateCreate();
    }

    @Override
    public String component9() {
        return getForgetPassword();
    }

    @Override
    public String component10() {
        return getActiveMail();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getHashValue();
    }

    @Override
    public String value3() {
        return getSalt();
    }

    @Override
    public String value4() {
        return getFullName();
    }

    @Override
    public Boolean value5() {
        return getGender();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getPhone();
    }

    @Override
    public Long value8() {
        return getDateCreate();
    }

    @Override
    public String value9() {
        return getForgetPassword();
    }

    @Override
    public String value10() {
        return getActiveMail();
    }

    @Override
    public UserRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setHashValue(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setSalt(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public UserRecord value5(Boolean value) {
        setGender(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UserRecord value8(Long value) {
        setDateCreate(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setForgetPassword(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setActiveMail(value);
        return this;
    }

    @Override
    public UserRecord values(String value1, String value2, String value3, String value4, Boolean value5, String value6, String value7, Long value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String username, String hashValue, String salt, String fullName, Boolean gender, String email, String phone, Long dateCreate, String forgetPassword, String activeMail) {
        super(User.USER);

        set(0, username);
        set(1, hashValue);
        set(2, salt);
        set(3, fullName);
        set(4, gender);
        set(5, email);
        set(6, phone);
        set(7, dateCreate);
        set(8, forgetPassword);
        set(9, activeMail);
    }
}
